---
title: "Create Word files"
author: "John Smith"
date: "February 6th,2017"
output:
  word_document: default
  html_notebook: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Description
This documentation gives an overview of your transactions during the last year.

<<<<<<< HEAD
=======


>>>>>>> 9348f66ba6fd6cb6ad371dfa28586fd8cfef4cd9
# Data overview
```{r data overview, include=FALSE}
library(data.table)
library(lubridate)
library(ggplot2)

myData <- fread("transactions.csv")
myData[, TransDate:=dmy(TransDate, tz="UTC")]

max(myData$TransDate)
myData <- myData[TransDate >= "2012-01-01",]
```

<<<<<<< HEAD

=======
>>>>>>> 9348f66ba6fd6cb6ad371dfa28586fd8cfef4cd9
```{r, echo = FALSE}
library(pander)
pander(summary(myData), caption = "Summary statistics", split.table = Inf, split.cells = c(6,8,5,7,7,9,6))
```


<<<<<<< HEAD
=======
# Number of transactions
Here we can see the ditribution of number of transactions per month over the last year.
```{r plot, include = FALSE}
myData[,month := as.numeric(format(TransDate, format = "%m"))]
myData[,month:=month.abb[month]]
```
>>>>>>> 9348f66ba6fd6cb6ad371dfa28586fd8cfef4cd9

```{r, echo = FALSE}
ggplot(myData, aes(x=month)) + geom_bar() +
  labs(x="", y="Transactions", title="Transactions per Month") +
  scale_x_discrete(labels=month.abb)

```

<<<<<<< HEAD
=======

# Literature
>>>>>>> 9348f66ba6fd6cb6ad371dfa28586fd8cfef4cd9
